metadata:
  name: client
  labels:
    app: client
spec:
 containers:
    name: client
    image: monasamir/client:m${BUILD_NUMBER}
    ports:
    containerPort: 3000 
service:
    type: NodePort 
    name: client-svc
    port:  3000
    targetPort: 3000 
    nodePort: 30057 
    protocol: TCP
