metadata:
  name: server
  labels:
    app: server
template:
  spec:
  containers:
  name: server
  image: monasamir/server:m${BUILD_NUMBER} 
    ports:
    - containerPort: 4000

service:
  metadata:  
   name: server-svc
  port: 4000
  targetPort: 4000
  protocol: TCP
   
        
    
